export default {
    resources: {
        login: "Username",
        password: "Password",
        registration: "Sing up",
        authorization: "Sing in",
        inputLogin: "Enter login",
        inputPassword: "Enter password",
        confirmPassword: "Repeat password",
        email: "Email",
        inputPhone: "Enter phone",
        inputKeyWord: "Enter key word",
        back: "Back",
        restorePassword: "Restore password",
        incorrectLogin: "Incorrect username",
        incorrectPassword: "Incorrect password",
        incorrectMail: "Incorrect e-mail",
        incorrectKeyWord: "Incorrect key word",
        successRegistration: "Success registration!",
        settings: "Settings",
        labelLanguage: "Choose language",
        keyWordMessage: "Needed to restore password",
        signIN: "Sign in",
    },
    dialogs: {
        forgotPassword: "Forgot password?",
        registrationText: 'Already has an account at WizardsChat',
        authorizationText: 'First at WizardsChat',
        goToLoginPage: 'Go to login page',
        goToRegistrationPage: 'Register a new account',
    }
}