export default {
    resources: {
        copyright: "© 2020 Все права защищены",
        team: "WeCan Team", 
        login: "Логин",
        password: "Пароль",
        registration: "Зарегистрироваться",
        authorization: "Войти",
        inputLogin: "Введите логин",
        inputPassword: "Введите пароль",
        confirmPassword: "Подтвердите пароль",
        inputEmail: "Введите e-mail",
        inputPhone: "Введите телефон",
        inputKeyWord: "Введите секретное слово",
        back: "Вернуться",
        restorePassword: "Восстановить пароль",
        incorrectLogin: "Некорректное имя пользователя",
        incorrectPassword: "Некорректный пароль",
        incorrectMail: "Некорректный e-mail",
        incorrectKeyWord: "Некорректное секретное слово",
        successRegistration: "Регистрация успешна!",
        settings: "Настройки",
        labelLanguage: "Выберите язык",
        keyWordMessage: "Необходим для восстановления пароля",
        signIN: "Войти",
    },
    dialogs: {
        forgotPassword: "Забыли пароль?",
        registrationText: 'Уже есть аккаунт в WizardsChat',
        authorizationText: 'Впервые в WizardsChat',
        goToLoginPage: 'Перейти на страницу входа',
        goToRegistrationPage: 'Зарегистрировать новый аккаунд',
    }
}