import keyMirror from "key-mirror";

export default keyMirror({
    CHANGE_MODE: null,
    CHANGE_MODE_ASYNC: null,
    CHANGE_LOCALE: null,
    LOGIN_REQUEST_ASYNC: null,
    REGISTRATION_REQUEST_ASYNC: null,
    SET_USER: null,
    SET_USERS: null,
    SET_USERS_ASYNC: null,
    INSERT_USER:null,
    INIT_USER: null,
    INIT_USER_ASYNC: null,
    CHANGE_USERS_FILTER: null,
    CHANGE_USERS_FILTER_ASYNC: null,
    UPDATE_PROFILE_ASYNC: null,
    UPDATE_IMAGE_ASYNC: null,
    SEND_MESSAGE: null,
    CREATE_SOCKET_CONNECTION: null,
    NEW_USER_CONNECTED: null,
    SET_ACTIVE_CHAT: null,
    SET_ACTIVE_CHAT_ASYNC: null,
    CREATE_CHAT_MESSAGE: null,
    USER_CONNECTED: null,
    CREATE_CHAT_MESSAGE_SUCCESS: null,
    NEW_MESSAGE_RECEIVED: null,
    CHANGE_SETTINGS_MODE: null,
    TOGGLE_IMOJI_STATE: null,
    CHANGE_MESSAGE_FILTER: null,
    CHANGE_MESSAGE_FILTER_ASYNC: null,
    USER_DISCONNECTED: null,
})